from __future__ import annotations

import contextlib
import io
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from agent_relay.cli import main
from agent_relay.errors import ConflictError, ValidationError
from agent_relay.models import AgentSpec
from agent_relay.presets import build_preset
from agent_relay.service import RelayService
from agent_relay.storage import RelayStore
from agent_relay.workspace import WorkspaceInspector, WorkspaceReview


WRITE_SCRIPT = r"""
import pathlib
import sys

pathlib.Path("generated.txt").write_text("generated by agent\n", encoding="utf-8")
if sys.argv[1] == "fail":
    raise SystemExit(7)
"""

WRITE_RESULT_SCRIPT = r"""
import json
import pathlib
import sys

prompt = sys.stdin.read()
payload = json.loads(prompt[prompt.index("{"):])
contract = payload["handoff"]["result_contract"]
result = dict(contract["schema"])
result["summary"] = "Reviewed workspace change"
result["files_changed"] = ["generated.txt"]
pathlib.Path("generated.txt").write_text("generated by agent\n", encoding="utf-8")
print(contract["begin_marker"])
print(json.dumps(result))
print(contract["end_marker"])
"""


class FailSecondSnapshotInspector(WorkspaceInspector):
    def __init__(self) -> None:
        super().__init__()
        self.snapshot_calls = 0

    def snapshot(self, workspace_root: Path):
        self.snapshot_calls += 1
        if self.snapshot_calls == 2:
            raise ValidationError("simulated post-run inspection failure")
        return super().snapshot(workspace_root)


class WorkspaceTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.workspace = self.root / "workspace"
        self.workspace.mkdir()
        self.git("init", "-q")
        self.git("config", "user.email", "relay@example.invalid")
        self.git("config", "user.name", "Agent Relay Tests")
        (self.workspace / "tracked.txt").write_text("original\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        self.git("commit", "-qm", "initial")
        self.inspector = WorkspaceInspector()

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def git(self, *arguments: str) -> str:
        completed = subprocess.run(
            ["git", "-C", str(self.workspace), *arguments],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return completed.stdout

    def test_snapshots_report_paths_and_hashes_without_file_contents(self) -> None:
        before = self.inspector.snapshot(self.workspace)
        (self.workspace / "generated.txt").write_text("secret payload\n", encoding="utf-8")
        after = self.inspector.snapshot(self.workspace)

        review = self.inspector.compare(before, after)
        serialized = json.dumps(review.to_dict())

        self.assertEqual(review.status, "pending")
        self.assertEqual(review.introduced_paths, ("generated.txt",))
        self.assertNotIn("secret payload", serialized)
        self.assertIn("Relay never deletes", serialized)

    def test_preexisting_staged_and_modified_paths_remain_distinguishable(self) -> None:
        (self.workspace / "tracked.txt").write_text("preexisting\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        before = self.inspector.snapshot(self.workspace)
        (self.workspace / "tracked.txt").write_text("agent edit\n", encoding="utf-8")
        after = self.inspector.snapshot(self.workspace)

        review = self.inspector.compare(before, after)

        self.assertEqual(review.preexisting_paths, ("tracked.txt",))
        self.assertEqual(review.modified_paths, ("tracked.txt",))
        self.assertTrue(before.files["tracked.txt"].staged)

    def test_staged_blob_changes_alter_the_hardened_snapshot_digest(self) -> None:
        tracked = self.workspace / "tracked.txt"
        tracked.write_text("staged-a\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        tracked.write_text("same-worktree\n", encoding="utf-8")
        before = self.inspector.snapshot(self.workspace)

        tracked.write_text("staged-b\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        tracked.write_text("same-worktree\n", encoding="utf-8")
        after = self.inspector.snapshot(self.workspace)

        review = self.inspector.compare(before, after)

        self.assertEqual(before.legacy_digest, after.legacy_digest)
        self.assertNotEqual(before.digest, after.digest)
        self.assertNotEqual(
            before.files["tracked.txt"].index_digest,
            after.files["tracked.txt"].index_digest,
        )
        self.assertEqual(before.files["tracked.txt"].index_entry_count, 1)
        self.assertEqual(review.status, "pending")
        self.assertEqual(review.modified_paths, ("tracked.txt",))
        self.assertEqual(review.snapshot_version, "2")

    def test_assume_unchanged_paths_fail_closed_before_snapshot(self) -> None:
        self.git("update-index", "--assume-unchanged", "tracked.txt")

        with self.assertRaisesRegex(ValidationError, "assume-unchanged"):
            self.inspector.snapshot(self.workspace)

    def test_skip_worktree_paths_fail_closed_before_snapshot(self) -> None:
        self.git("update-index", "--skip-worktree", "tracked.txt")

        with self.assertRaisesRegex(ValidationError, "skip-worktree"):
            self.inspector.snapshot(self.workspace)

    def test_ignored_file_changes_are_included_in_review(self) -> None:
        (self.workspace / ".gitignore").write_text("ignored.txt\n", encoding="utf-8")
        self.git("add", ".gitignore")
        self.git("commit", "-qm", "ignore generated file")
        before = self.inspector.snapshot(self.workspace)
        (self.workspace / "ignored.txt").write_text("ignored content\n", encoding="utf-8")
        after = self.inspector.snapshot(self.workspace)

        review = self.inspector.compare(before, after)

        self.assertEqual(review.introduced_paths, ("ignored.txt",))

    def test_exact_git_root_and_review_paths_fail_closed(self) -> None:
        nested = self.workspace / "nested"
        nested.mkdir()

        with self.assertRaises(ValidationError):
            self.inspector.validate_root(nested)
        with self.assertRaises(ValidationError):
            WorkspaceReview.from_dict(
                {
                    "status": "pending",
                    "workspace_root": str(self.workspace),
                    "before_digest": "a" * 64,
                    "after_digest": "b" * 64,
                    "before_head": "a" * 40,
                    "after_head": "a" * 40,
                    "before_branch": "main",
                    "after_branch": "main",
                    "introduced_paths": ["../escape"],
                }
            )

    def test_review_without_snapshot_version_loads_as_legacy(self) -> None:
        review = WorkspaceReview.from_dict(
            {
                "status": "clean",
                "workspace_root": str(self.workspace),
                "before_digest": "a" * 64,
                "after_digest": "a" * 64,
                "before_head": "b" * 40,
                "after_head": "b" * 40,
                "before_branch": "main",
                "after_branch": "main",
            }
        )

        self.assertEqual(review.snapshot_version, "1")

    def test_legacy_digest_matching_fails_closed_when_index_is_staged(self) -> None:
        clean = self.inspector.snapshot(self.workspace)
        legacy_review = WorkspaceReview(
            status="clean",
            workspace_root=str(self.workspace),
            before_digest=clean.legacy_digest,
            after_digest=clean.legacy_digest,
            before_head=clean.head,
            after_head=clean.head,
            before_branch=clean.branch,
            after_branch=clean.branch,
            snapshot_version="1",
        )

        self.assertTrue(
            RelayService._workspace_digest_matches(
                legacy_review,
                clean,
                clean.legacy_digest,
            )
        )

        (self.workspace / "tracked.txt").write_text("staged\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        staged = self.inspector.snapshot(self.workspace)
        with self.assertRaisesRegex(ConflictError, "legacy workspace reviews"):
            RelayService._workspace_digest_matches(
                legacy_review,
                staged,
                staged.legacy_digest,
            )


class WorkspaceServiceTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.workspace = self.root / "workspace"
        self.workspace.mkdir()
        self.git("init", "-q")
        self.git("config", "user.email", "relay@example.invalid")
        self.git("config", "user.name", "Agent Relay Tests")
        (self.workspace / "tracked.txt").write_text("original\n", encoding="utf-8")
        self.git("add", "tracked.txt")
        self.git("commit", "-qm", "initial")
        self.store = RelayStore(self.root / "state")
        self.service = RelayService(self.store)
        self.service.register_agent(
            AgentSpec("source", "Source", (sys.executable, "-c", "print('source')"))
        )
        self.service.register_agent(
            AgentSpec("reader", "Reader", (sys.executable, "-c", "print('reader')"))
        )
        self.service.register_agent(
            AgentSpec(
                "route-reader",
                "Route reader",
                (sys.executable, "-c", "print('reader')"),
                capabilities=("repo-read",),
                provider_id="codex-cli",
            )
        )
        self.register_writer("writer", "success")

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def git(self, *arguments: str) -> str:
        completed = subprocess.run(
            ["git", "-C", str(self.workspace), *arguments],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        return completed.stdout

    def register_writer(self, agent_id: str, mode: str) -> None:
        self.service.register_agent(
            AgentSpec(
                agent_id=agent_id,
                display_name="Writer",
                command=(sys.executable, "-c", WRITE_SCRIPT, mode),
                capabilities=("repo-read", "repo-write"),
                provider_id="codex-cli-write",
                permission_profile="workspace-write",
            )
        )

    def new_task(self):
        return self.service.create_task(
            "Write safely",
            "Make one reviewed change",
            active_agent="source",
        )

    def test_write_requires_both_reviewed_preset_and_task_authorization(self) -> None:
        task = self.new_task()

        with self.assertRaises(ConflictError):
            self.service.preview_handoff(task.task_id, "writer")
        with self.assertRaises(ValidationError):
            self.service.authorize_workspace(task.task_id, "reader", self.workspace)
        with self.assertRaises(ValidationError):
            self.service.authorize_workspace(
                task.task_id,
                "writer",
                self.workspace / "not-the-root",
            )
        self.assertEqual(self.store.get_task(task.task_id).actions, [])

    def test_authorization_is_task_agent_specific_and_revocable(self) -> None:
        first = self.new_task()
        second = self.new_task()
        self.service.authorize_workspace(first.task_id, "writer", self.workspace)

        with self.assertRaises(ConflictError):
            self.service.preview_handoff(second.task_id, "writer")
        revoked = self.service.revoke_workspace(first.task_id, "writer")
        self.assertEqual(revoked.actions[-1].kind, "workspace-write-revoke")
        with self.assertRaises(ConflictError):
            self.service.preview_handoff(first.task_id, "writer")

    def test_write_agent_cannot_be_added_to_an_automatic_route(self) -> None:
        task = self.service.create_task(
            "Read route",
            "Keep fallback read-only",
            active_agent="route-reader",
        )

        with self.assertRaises(ValidationError):
            self.service.configure_route(task.task_id, ["route-reader", "writer"])

    def test_claude_write_preset_reuses_authorization_and_review_gates(self) -> None:
        executable = self.root / "claude-writer"
        executable.write_text(
            "#!/usr/bin/env python3\n"
            "from pathlib import Path\n"
            "Path('claude-generated.txt').write_text('generated by Claude\\n', "
            "encoding='utf-8')\n"
            "print('completed')\n",
            encoding="utf-8",
        )
        executable.chmod(0o700)
        self.service.register_agent(
            build_preset(
                "claude-code-write",
                agent_id="claude-writer",
                executable=str(executable),
            )
        )
        route_task = self.service.create_task(
            "Keep writes out of routes",
            "Reject automatic workspace mutation",
            active_agent="route-reader",
        )
        with self.assertRaises(ValidationError):
            self.service.configure_route(
                route_task.task_id,
                ["route-reader", "claude-writer"],
            )
        task = self.new_task()

        with self.assertRaises(ConflictError):
            self.service.preview_handoff(task.task_id, "claude-writer")

        self.service.authorize_workspace(
            task.task_id,
            "claude-writer",
            self.workspace,
        )
        outcome = self.service.handoff(
            task.task_id,
            "claude-writer",
            self.workspace,
        )

        self.assertEqual(outcome.execution.status, "completed")
        self.assertEqual(outcome.task.status, "blocked")
        self.assertEqual(outcome.task.active_agent, "claude-writer")
        self.assertEqual(
            outcome.workspace_review.introduced_paths,
            ("claude-generated.txt",),
        )
        with self.assertRaises(ConflictError):
            self.service.handoff(task.task_id, "reader", self.workspace)

    def test_unbounded_provider_write_profiles_are_rejected(self) -> None:
        for provider_id in ("gemini-cli-write", "antigravity-cli-write"):
            agent_id = provider_id + "-candidate"
            self.service.register_agent(
                AgentSpec(
                    agent_id=agent_id,
                    display_name="Unbounded candidate",
                    command=(sys.executable, "-c", "print('unsafe')"),
                    capabilities=("repo-read", "repo-write"),
                    provider_id=provider_id,
                    permission_profile="workspace-write",
                )
            )
            task = self.new_task()

            with self.subTest(provider_id=provider_id), self.assertRaises(
                ValidationError
            ):
                self.service.authorize_workspace(
                    task.task_id,
                    agent_id,
                    self.workspace,
                )

    def test_successful_write_blocks_until_unchanged_review_is_accepted(self) -> None:
        task = self.new_task()
        authorized = self.service.authorize_workspace(
            task.task_id,
            "writer",
            self.workspace,
        )
        self.assertEqual(authorized.actions[-1].kind, "workspace-write-authorize")
        preview = self.service.preview_handoff(task.task_id, "writer")
        self.assertIn('"mode": "workspace-write"', preview.prompt)

        outcome = self.service.handoff(task.task_id, "writer", self.workspace)

        self.assertEqual(outcome.task.status, "blocked")
        self.assertEqual(outcome.task.active_agent, "writer")
        self.assertEqual(outcome.workspace_review.status, "pending")
        self.assertEqual(outcome.workspace_review.introduced_paths, ("generated.txt",))
        action = outcome.task.actions[-1]
        self.assertEqual(action.kind, "workspace-write")
        self.assertNotIn("generated by agent", json.dumps(action.to_dict()))
        with self.assertRaises(ConflictError):
            self.service.handoff(task.task_id, "reader", self.workspace)

        inspected = self.service.inspect_workspace_review(task.task_id, action.action_id)
        accepted = self.service.accept_workspace_review(
            task.task_id,
            action.action_id,
            inspected.task.revision,
            self.workspace,
        )

        self.assertEqual(accepted.status, "active")
        self.assertEqual(
            accepted.actions[-2].details["workspace_review"]["status"],
            "accepted",
        )
        self.assertEqual(accepted.actions[-1].kind, "workspace-write-accept")

    def test_write_result_waits_for_workspace_review_before_memory_acceptance(self) -> None:
        self.service.register_agent(
            AgentSpec(
                agent_id="result-writer",
                display_name="Result writer",
                command=(sys.executable, "-c", WRITE_RESULT_SCRIPT),
                capabilities=("repo-read", "repo-write"),
                provider_id="codex-cli-write",
                permission_profile="workspace-write",
            )
        )
        task = self.new_task()
        self.service.authorize_workspace(task.task_id, "result-writer", self.workspace)
        outcome = self.service.handoff(task.task_id, "result-writer", self.workspace)

        self.assertEqual(outcome.result_status, "pending")
        with self.assertRaises(ConflictError):
            self.service.accept_result(
                task.task_id,
                outcome.action_id,
                outcome.task.revision,
            )
        reviewed = self.service.accept_workspace_review(
            task.task_id,
            outcome.action_id,
            outcome.task.revision,
            self.workspace,
        )
        preview = self.service.preview_result(task.task_id, outcome.action_id)
        accepted = self.service.accept_result(
            task.task_id,
            outcome.action_id,
            preview.task.revision,
        )

        self.assertEqual(reviewed.status, "active")
        self.assertEqual(accepted.state.summary, "Reviewed workspace change")
        self.assertEqual(accepted.state.files_changed, ["generated.txt"])

    def test_changed_snapshot_cannot_be_accepted_and_can_be_rolled_back(self) -> None:
        task = self.new_task()
        self.service.authorize_workspace(task.task_id, "writer", self.workspace)
        outcome = self.service.handoff(task.task_id, "writer", self.workspace)
        action_id = outcome.action_id
        (self.workspace / "generated.txt").write_text("changed later\n", encoding="utf-8")

        with self.assertRaises(ConflictError):
            self.service.accept_workspace_review(
                task.task_id,
                action_id,
                outcome.task.revision,
                self.workspace,
            )

        (self.workspace / "generated.txt").unlink()
        rolled_back = self.service.verify_workspace_rollback(
            task.task_id,
            action_id,
            outcome.task.revision,
            self.workspace,
        )

        self.assertEqual(rolled_back.status, "active")
        self.assertEqual(rolled_back.active_agent, "source")
        self.assertEqual(
            rolled_back.actions[-2].details["workspace_review"]["status"],
            "rolled-back",
        )

    def test_ambiguous_write_failure_never_falls_back_or_resolves_without_rollback(self) -> None:
        self.register_writer("failing-writer", "fail")
        task = self.new_task()
        self.service.authorize_workspace(
            task.task_id,
            "failing-writer",
            self.workspace,
        )

        outcome = self.service.handoff(task.task_id, "failing-writer", self.workspace)

        self.assertEqual(outcome.execution.status, "unknown")
        self.assertEqual(outcome.task.status, "blocked")
        self.assertEqual(outcome.task.active_agent, "source")
        self.assertEqual(outcome.workspace_review.status, "pending")
        with self.assertRaises(ConflictError):
            self.service.resolve_action(task.task_id, outcome.action_id, "failed")
        with self.assertRaises(ConflictError):
            self.service.accept_workspace_review(
                task.task_id,
                outcome.action_id,
                outcome.task.revision,
                self.workspace,
            )

        (self.workspace / "generated.txt").unlink()
        recovered = self.service.verify_workspace_rollback(
            task.task_id,
            outcome.action_id,
            outcome.task.revision,
            self.workspace,
        )
        self.assertEqual(recovered.actions[-2].status, "cancelled")
        self.assertEqual(recovered.status, "active")

    def test_write_process_that_never_launches_records_clean_failure(self) -> None:
        self.service.register_agent(
            AgentSpec(
                agent_id="missing-writer",
                display_name="Missing writer",
                command=(str(self.root / "does-not-exist"),),
                capabilities=("repo-read", "repo-write"),
                provider_id="codex-cli-write",
                permission_profile="workspace-write",
            )
        )
        task = self.new_task()
        self.service.authorize_workspace(task.task_id, "missing-writer", self.workspace)

        outcome = self.service.handoff(task.task_id, "missing-writer", self.workspace)

        self.assertFalse(outcome.execution.started)
        self.assertEqual(outcome.workspace_review.status, "clean")
        self.assertEqual(outcome.task.actions[-1].status, "failed")
        self.assertEqual(outcome.task.status, "active")
        self.assertEqual(outcome.task.active_agent, "source")

    def test_post_run_inspection_failure_blocks_until_verified_rollback(self) -> None:
        self.service.workspace_inspector = FailSecondSnapshotInspector()
        task = self.new_task()
        self.service.authorize_workspace(task.task_id, "writer", self.workspace)

        outcome = self.service.handoff(task.task_id, "writer", self.workspace)

        self.assertEqual(outcome.task.status, "blocked")
        self.assertEqual(outcome.task.actions[-1].status, "unknown")
        self.assertEqual(outcome.workspace_review.status, "unavailable")
        self.assertEqual(
            outcome.workspace_review.error_code,
            "post-run-workspace-inspection-failed",
        )
        (self.workspace / "generated.txt").unlink()
        recovered = self.service.verify_workspace_rollback(
            task.task_id,
            outcome.action_id,
            outcome.task.revision,
            self.workspace,
        )
        self.assertEqual(recovered.status, "active")

    def test_cli_exposes_authorize_review_and_accept_flow(self) -> None:
        task = self.new_task()
        stdout = io.StringIO()
        stderr = io.StringIO()
        with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            status = main(
                [
                    "--state-dir",
                    str(self.root / "state"),
                    "workspace",
                    "authorize",
                    task.task_id,
                    "writer",
                    "--root",
                    str(self.workspace),
                ]
            )
        self.assertEqual(status, 0, stderr.getvalue())
        self.assertEqual(
            json.loads(stdout.getvalue())["authorization_action"]["kind"],
            "workspace-write-authorize",
        )

        outcome = self.service.handoff(task.task_id, "writer", self.workspace)
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            status = main(
                [
                    "--state-dir",
                    str(self.root / "state"),
                    "workspace",
                    "review",
                    task.task_id,
                    outcome.action_id,
                ]
            )
        self.assertEqual(status, 0)
        review_output = json.loads(stdout.getvalue())
        self.assertEqual(review_output["workspace_review"]["status"], "pending")
        self.assertTrue(review_output["workspace_review"]["rollback_guidance"])

        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            status = main(
                [
                    "--state-dir",
                    str(self.root / "state"),
                    "workspace",
                    "accept",
                    task.task_id,
                    outcome.action_id,
                    "--expected-revision",
                    str(review_output["checkpoint_revision"]),
                    "--cwd",
                    str(self.workspace),
                ]
            )
        self.assertEqual(status, 0)
        self.assertEqual(json.loads(stdout.getvalue())["task"]["status"], "active")


if __name__ == "__main__":
    unittest.main()
